footprint: [[-0.12, -0.22], [-0.12, 0.22], [0.25, 0.22], [0.25, -0.22]]
#robot_radius: 0.2
inflation_radius: 0.2
#cost_scaling_factor: 3.0
#max_obstacle_height: 2.0
min_obstacle_height: 0.1
obstacle_range: 3.5
raytrace_range: 4.0

obstacle_layer:
    observation_sources: laser_scan_sensor
#    laser_scan_sensor: {sensor_frame: scanner_link, data_type: LaserScan, topic: scan, marking: true, clearing: true}
    laser_scan_sensor: {sensor_frame: kinect_depth_frame, data_type: LaserScan, topic: base_scan, marking: true, clearing: true}
