right_joints: [right_j1_joint, right_j2_joint, right_j3_joint, right_j4_joint, right_j5_joint, right_j6_joint]

left_joints: [left_j1_joint, left_j2_joint, left_j3_joint, left_j4_joint, left_j5_joint, left_j6_joint]

head_tilt_joint:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: head_tilt_joint
    joint_speed: 0.5
    motor:
        id: 7
        init: 512
        min: 1023
        max: 50

head_pan_joint:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: head_pan_joint
    joint_speed: 0.5
    motor:
        id: 3
        init: 512
        min: 50
        max: 900

right_j3_joint_joint:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_j3_joint_joint
    joint_speed: 0.5
    motor:
        id: 9
        init: 512
        min: 900
        max: 50
right_j4_joint:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_j4_joint
    joint_speed: 0.5
    motor:
        id: 6
        init: 512
        min: 0
        max: 900
right_j5_joint:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_j5_joint
    joint_speed: 0.5
    motor:
        id: 2
        init: 512
        min: 5
        max: 900
right_j6_joint:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_j6_joint
    joint_speed: 0.5
    motor:
        id: 5
        init: 512
        min: 0
        max: 900

left_j4_joint:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: left_j4_joint
    joint_speed: 0.5
    motor:
        id: 8
        init: 512
        min: 900
        max: 50
left_j5_joint:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: left_j5_joint
    joint_speed: 0.5
    motor:
        id: 4
        init: 512
        min: 900
        max: 50
left_j6_joint:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: left_j6_joint
    joint_speed: 0.5
    motor:
        id: 10
        init: 512
        min: 50
        max: 900
