global_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 5.0
  static_map: true
  inflation_layer/inflation_radius: 0.1
  inflation_layer/cost_scaling_factor: 1.5
  plugins:
    - {name: static_map,        type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,    type: "costmap_2d::ObstacleLayer", output: "screen"}
    - {name: inflation_layer,   type: "costmap_2d::InflationLayer", output: "screen"}
