local_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 8.0
  publish_frequency: 4.0
  rolling_window: true
  static_map: false
  width: 6.0
  height: 6.0
  resolution: 0.05
  min_obstacle_height: 0.1
  inflation_layer/inflation_radius: 0.1
  inflation_layer/cost_scaling_factor: 1.5
  plugins:
    - {name: obstacle_layer,         type: "costmap_2d::ObstacleLayer", output: "screen"}
    - {name: inflation_layer,        type: "costmap_2d::InflationLayer", output: "screen"}
   
