controller_frequency: 2.0
recovery_behavior_enabled: false
clearing_rotation_allowed: false

TrajectoryPlannerROS:
   max_vel_x: 0.15
   min_vel_x: 0.05
   max_vel_y: 0.0  # zero for a differential drive robot
   min_vel_y: 0.0
   max_rotational_vel: 0.05
   min_in_place_vel_theta: 0.05
   escape_vel: -0.1
   acc_lim_x: 1.5
   acc_lim_y: 0.0  # zero for a differential drive robot
   acc_lim_theta: 0.1 # try 10

   holonomic_robot: false
   yaw_goal_tolerance: 0.3 # about 6 degrees
   xy_goal_tolerance: 0.1 # 5 cm
   latch_xy_goal_tolerance: false
   pdist_scale: 2
   gdist_scale: 2
   meter_scoring: true

   heading_lookahead: 0.325
  
   heading_scoring_timestep: 0.8
   occdist_scale: 0.05
   oscillation_reset_dist: 0.05
   publish_cost_grid_pc: false
   prune_plan: true

   sim_time: 10
   sim_granularity: 0.05
   angular_sim_granularity: 0.1
   vx_samples: 10
   vy_samples: 0  # zero for a differential drive robot
   vtheta_samples: 20
   dwa: false
   heading_scoring: true
   simple_attractor: true
   publish_cost_grid:    true 
   prune_plan:           false
   
