<?xml version="1.0"?>

<!-- XML namespaces -->
  <robot name="gizmo" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="PI" value="3.1415" />  
    <xacro:property name="M_PI" value="3.14159"/>
    <xacro:property name="M_SCALE" value="0.001"/>
    <xacro:property name="C_SCALE" value="0.0034"/>
    <xacro:property name="MESH_EXT" value="stl"/>
    <xacro:property name="color" value="grey1"/>
    <xacro:include filename="$(find gizmo_description)/urdf/hardware.xacro" />
    <xacro:include filename="$(find gizmo_description)/urdf/dynamixel_arm_hardware.xacro" />
    <xacro:include filename="$(find gizmo_description)/urdf/mantis_gripper.xacro" />



<xacro:my_box name="base_footprint" lwh="0.1 0.1 0.005" xyz="0 0 0" rpy="0 0 0" mass="0.1" material="Gazebo/FlatBlack">
	        <xacro:gold />
        </xacro:my_box>

<link name="base_link" >
   <visual>
      <geometry>
        <mesh filename="package://gizmo_description/meshes/gizmo_base2.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
      </geometry>
         <xacro:White/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </visual>
   <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://gizmo_description/meshes/gizmo_base2.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
          </geometry>
      </collision>
  </link>

<xacro:my_cylinder name="left_wheel" l="0.035" r="0.075" xyz="0 0 0" rpy="1.57 0 0" mass="0.1" material="Gazebo/Grey">
		<xacro:grey1 />
	</xacro:my_cylinder>

  <xacro:my_cylinder name="right_wheel" l="0.035" r="0.075" xyz="0 0 0" rpy="1.57 0 0" mass="0.1" material="Gazebo/Grey">
		<xacro:grey1 />
	</xacro:my_cylinder>

  <link name="kinect_link">
      <inertial>
        <mass value="1.0" />
        <origin xyz="0 0 0" />
        <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                 iyy="1.0" iyz="0.0"
                 izz="1.0" />
      </inertial>

      <visual>
        <origin xyz=" 0 0 0 " rpy="0 0 0" />
        <geometry>
          <mesh filename="package://gizmo_description/meshes/kinect.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
        </geometry>
        <xacro:ax12_color />
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://gizmo_description/meshes/kinect.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
          </geometry>
      </collision>

    </link>


<link name="torso_link" >
   <visual>
      <geometry>
        <mesh filename="package://gizmo_description/meshes/gizmo_torso3.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
      </geometry>
         <xacro:grey1/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </visual>
    <collision>
        <origin xyz="-0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://gizmo_description/meshes/gizmo_torso3.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
          </geometry>
      </collision>
  </link>

<xacro:ax12 name="pan_link" xyz="0 0 0" rpy=" 1.57 0 1.57">
	</xacro:ax12>

<xacro:my_box name="head_pan_link" lwh="0.15 0.1 0.005" xyz="0 0 0" rpy="0 0 0" mass="0.1" material="Gazebo/FlatBlack">
	        <xacro:blue />
        </xacro:my_box>

<xacro:ax12 name="head_tilt_link" xyz="0 0 0" rpy="0 0 3.14">
	</xacro:ax12>

<xacro:F2_bracket name="head_tilt_bracket_f2" xyz="0 0 0" rpy="0 0 0" />

<link name="neck" >
   <visual>
      <geometry>
        <mesh filename="package://gizmo_description/meshes/gizmo_neck1.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
      </geometry>
         <xacro:grey1/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </visual>
    <collision>
        <origin xyz="-0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://gizmo_description/meshes/gizmo_neck1.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
          </geometry>
      </collision>
  </link>

<link name="head" >
   <visual>
      <geometry>
        <mesh filename="package://gizmo_description/meshes/head1.stl" scale="${C_SCALE} ${C_SCALE} ${C_SCALE}"/>
      </geometry>
         <xacro:grey1/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </visual>
    <collision>
        <origin xyz="-0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://gizmo_description/meshes/head1.stl" scale="${C_SCALE} ${C_SCALE} ${C_SCALE}"/>
          </geometry>
      </collision>
  </link>
<xacro:my_cylinder name="camera_link" l="0.025" r="0.01" xyz="0 0 0" rpy="0 1.57 0" mass="0.1" material="Gazebo/Grey">		
      <xacro:grey1 />
	</xacro:my_cylinder>

<xacro:my_sphere name="right_rotate" r="0.03" xyz="0 0 0" rpy="0 0 0" mass="0.1" material="Gazebo/Grey">		
      <xacro:grey1 />
	</xacro:my_sphere>

<xacro:my_sphere name="left_rotate" r="0.03" xyz="0 0 0" rpy="0 0 0" mass="0.1" material="Gazebo/Grey">		
      <xacro:grey1 />
	</xacro:my_sphere>


<xacro:my_box name="right_lift_link" lwh="0.11 0.01 0.03" xyz="0.055 0 0" rpy="0 0 0" mass="0.1" material="Gazebo/FlatBlack">
	        <xacro:grey1 />
        </xacro:my_box>
<xacro:my_box name="left_lift_link" lwh="0.11 0.01 0.03" xyz="0.055 0 0" rpy="0 0 0" mass="0.1" material="Gazebo/FlatBlack">
	        <xacro:grey1 />
        </xacro:my_box>

<!--############################# right arm ################-->

<joint name="right_rotate_joint" type="revolute">
    	<parent link="torso_link" />
    	<child link="right_rotate" />
        <origin xyz="-0.065 -0.16 0.7" rpy="0 0 0" />
    	<axis xyz="0 0 1" />
    	<limit lower="-0.89" upper="1.41" effort="10" velocity="1" />
      	<dynamics damping="0.0"/>
	</joint>

<joint name="right_lift_joint" type="revolute">
    	<parent link="right_rotate" />
    	<child link="right_lift_link" />
        <origin xyz="0 -0.015 0" rpy="0 0 0" />
    	<axis xyz="0 1 0" />
    	<limit lower="-2" upper="2" effort="10" velocity="1" />
      	<dynamics damping="0.0"/>
	</joint>

<!-- shoulder roll -->
    <bioloid_F3_fixed parent="right_lift" name="right_arm_shoulder_F3_1" color="${color}">
      <origin xyz="0.115 0 0" rpy="0 1.57 0" />
    </bioloid_F3_fixed>
    
    <dynamixel_AX12_revolute parent="right_arm_shoulder_F3_1" name="right_arm_shoulder_roll" vlimit="3.14" llimit="-3.14" ulimit="3.14">
      <origin xyz="0 0 ${AX12_HEIGHT/2}" rpy="${-PI/2} 0 ${-PI/2}" />
      <axis xyz="0 1 0" />
    </dynamixel_AX12_revolute>
    
    <bioloid_F3_fixed parent="right_arm_shoulder_roll" name="right_arm_shoulder_roll_F3_0" color="${color}">
      <origin xyz="${AX12_WIDTH/2} 0 ${-(AX12_DEPTH - F3_WIDTH)/2}" rpy="0 ${PI/2} 0" />
    </bioloid_F3_fixed>

    <bioloid_F9_fixed parent="right_arm_shoulder_roll_F3_0" name="right_arm_shoulder_roll_F9_0" color="${color}">
      <origin xyz="0 ${-F9_DEPTH/2 - 0.000} ${-F9_DEPTH/2 + 0.004}" rpy="0 ${PI/2} 0" />
    </bioloid_F9_fixed>
    
    <!-- elbow flex -->
    <bioloid_F3_fixed parent="right_arm_shoulder_roll_F9_0" name="right_arm_elbow_F3_0" color="${color}">
      <origin xyz="0 ${-AX12_HEIGHT/2 + 0.0035} 0" rpy="${PI/2} ${PI} ${PI}" />
    </bioloid_F3_fixed>
    
    <dynamixel_AX12_fixed parent="right_arm_elbow_F3_0" name="right_arm_elbow_flex_servo">
      <origin xyz="0 0 ${-(AX12_WIDTH + F3_HEIGHT/2)}" rpy="0 ${PI} 0" />
    </dynamixel_AX12_fixed>
    
    <bioloid_F2_revolute parent="right_arm_elbow_flex_servo" name="right_arm_elbow_flex" color="${color}" vlimit="3.14" llimit="-1.75" ulimit="1.75">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <axis xyz="0 1 0" />
    </bioloid_F2_revolute>
    
    <!-- forearm flex -->
    <bioloid_F3_fixed parent="right_arm_elbow_flex" name="right_arm_forearm_F3_0" color="${color}">
      <origin xyz="0 0 ${AX12_HEIGHT/2 + F3_HEIGHT - 0.0015}" rpy="${PI} 0 ${PI/2}" />
    </bioloid_F3_fixed>
    
    <dynamixel_AX12_fixed parent="right_arm_forearm_F3_0" name="right_arm_forearm_flex_servo">
      <origin xyz="0 0 ${-(AX12_HEIGHT/2 + F2_DEPTH)}" rpy="${PI} 0 0" />
    </dynamixel_AX12_fixed>
    
    <bioloid_F2_revolute parent="right_arm_forearm_flex_servo" name="right_arm_forearm_flex" color="${color}" vlimit="3.14" llimit="-1.75" ulimit="1.75">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <axis xyz="0 1 0" />
    </bioloid_F2_revolute>
    
    <bioloid_F2_fixed parent="right_arm_forearm_flex" name="right_arm_forearm_F2_0" color="${color}">
      <origin xyz="0 0 ${AX12_HEIGHT/2 + F2_HEIGHT - 0.004}" rpy="0 ${PI} ${PI/2}" />
    </bioloid_F2_fixed>
    
    <!-- wrist flex -->
    <dynamixel_AX12_revolute parent="right_arm_forearm_F2_0" name="right_arm_wrist_flex" vlimit="3.14" llimit="-1.75" ulimit="1.75">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <axis xyz="0 1 0" />
    </dynamixel_AX12_revolute>
    
    <bioloid_F3_fixed parent="right_arm_wrist_flex" name="right_arm_wrist_F3_0" color="${color}">
      <origin xyz="0 0 ${-AX12_HEIGHT - F3_HEIGHT/2}" rpy="${PI} 0 0" />
    </bioloid_F3_fixed>
    
    <!-- gripper attach joint -->
    <bioloid_F3_fixed parent="right_arm_wrist_F3_0" name="right_arm_gripper_attach" color="${color}">
      <origin xyz="0 0 0.0005" rpy="${PI} 0 0" />
    </bioloid_F3_fixed>

   <!-- Attach the right gripper -->
   <gripper side="right" reflect="1" parent="_arm_gripper_attach_link">
     <origin xyz="0 0 0" rpy="0 0 0" /> 
   </gripper>
  
 

<!-- ##############################   joints ##################333333--> 

<joint name="base_footprint" type="fixed">
    	<parent link="base_footprint" />
    	<child link="base_link" />
    	<origin xyz="0.06 0 0.1" rpy="0 0 0" />
	</joint> 

 <joint name="base_link_left_wheel_joint" type="fixed">
    	<parent link="base_link" />
    	<child link="left_wheel" />
    	<origin xyz="0.03 -0.14 -0.02" rpy="0 0 0" />
	</joint>

  <joint name="base_link_right_wheel_joint" type="fixed">
    	<parent link="base_link" />
    	<child link="right_wheel" />
    	<origin xyz="0.03 0.14 -0.02" rpy="0 0 0" />
	</joint>
    
 

<joint name="torso_link" type="fixed">
    	<parent link="base_link" />
    	<child link="torso_link" />
    	<origin xyz="0.0 0 0" rpy="0 0 0" />
	</joint> 

<joint name="pan_link" type="fixed">
    	<parent link="torso_link" />
    	<child link="pan_link" />
    	<origin xyz="-0.06 0 0.75" rpy="0 0 0" />
	</joint> 


<!-- head_pan_joint-->	
	<joint name="head_pan_joint" type="revolute">
    	<parent link="pan_link" />
    	<child link="head_pan_link" />
    	<origin xyz="-0.04 0 0.02" rpy="0 0 3.14159" />
        <origin xyz="0 0 0.0" rpy="0 0 0" />
    	<axis xyz="0 0 1" />
    	<limit lower="-2" upper="2" effort="10" velocity="1" />
      	<dynamics damping="0.0"/>
	</joint>

<!-- head_tilt_servo-->	
	<joint name="head_tilt_link" type="fixed">
    	<parent link="head_pan_link" />
    	<child link="head_tilt_link" />
    	<origin xyz="-0.06 0 0.04" rpy="0 0 0" />
      
	</joint>

<!-- head_tilt_joint-->	
	<joint name="head_tilt_joint" type="revolute">
    	<parent link="head_tilt_link" />
    	<child link="head_tilt_bracket_f2" />
        <origin xyz="0 0 0.0" rpy="0 0 3.14" />
    	<axis xyz="0 1 0" />
    	<limit lower="2" upper="-2" effort="10" velocity="1" />
      	<dynamics damping="0.0"/>
	</joint>

<!-- neck-->	
	<joint name="neck_link" type="fixed">
    	<parent link="head_tilt_bracket_f2" />
    	<child link="neck" />
    	<origin xyz="0 0 0.02" rpy="0 0 0" />   
	</joint>

<!-- head-->	
	<joint name="head_link" type="fixed">
    	<parent link="neck" />
    	<child link="head" />
    	<origin xyz="0 0 0.05" rpy="0 0 0" />   
	</joint>

<!-- camera-->	
	<joint name="camera_link" type="fixed">
    	<parent link="head" />
    	<child link="camera_link" />
    	<origin xyz="0.065 0.055 0.005" rpy="0 0 3.14159" />   
	</joint>




   

<!--############################# left arm ################-->

<joint name="left_rotate_joint" type="revolute">
    	<parent link="torso_link" />
    	<child link="left_rotate" />
        <origin xyz="-0.065 0.16 0.7" rpy="0 0 0" />
    	<axis xyz="0 0 1" />
    	<limit lower="-1.34" upper="1.15" effort="10" velocity="1" />
      	<dynamics damping="0.0"/>
	</joint>

<joint name="left_lift_joint" type="revolute">
    	<parent link="left_rotate" />
    	<child link="left_lift_link" />
        <origin xyz="0 0.015 0" rpy="0 0 0" />
    	<axis xyz="0 1 0" />
    	<limit lower="-1.57" upper="1.57" effort="10" velocity="1" />
      	<dynamics damping="0.0"/>
	</joint>

<!-- left shoulder roll -->
    <bioloid_F3_fixed parent="left_lift" name="left_arm_shoulder_F3_1" color="${color}">
      <origin xyz="0.115 0 0" rpy="0 1.57 0" />
    </bioloid_F3_fixed>
    
    <dynamixel_AX12_revolute parent="left_arm_shoulder_F3_1" name="left_arm_shoulder_roll" vlimit="3.14" llimit="-3.14" ulimit="3.14">
      <origin xyz="0 0 ${AX12_HEIGHT/2}" rpy="${-PI/2} 0 ${-PI/2}" />
      <axis xyz="0 1 0" />
    </dynamixel_AX12_revolute>
    
    <bioloid_F3_fixed parent="left_arm_shoulder_roll" name="left_arm_shoulder_roll_F3_0" color="${color}">
      <origin xyz="${AX12_WIDTH/2} 0 ${-(AX12_DEPTH - F3_WIDTH)/2}" rpy="0 ${PI/2} 0" />
    </bioloid_F3_fixed>

    <bioloid_F9_fixed parent="left_arm_shoulder_roll_F3_0" name="left_arm_shoulder_roll_F9_0" color="${color}">
      <origin xyz="0 ${-F9_DEPTH/2 - 0.000} ${-F9_DEPTH/2 + 0.004}" rpy="0 ${PI/2} 0" />
    </bioloid_F9_fixed>
    
    <!-- left elbow flex -->
    <bioloid_F3_fixed parent="left_arm_shoulder_roll_F9_0" name="left_arm_elbow_F3_0" color="${color}">
      <origin xyz="0 ${-AX12_HEIGHT/2 + 0.0035} 0" rpy="${PI/2} ${PI} ${PI}" />
    </bioloid_F3_fixed>
    
    <dynamixel_AX12_fixed parent="left_arm_elbow_F3_0" name="left_arm_elbow_flex_servo">
      <origin xyz="0 0 ${-(AX12_WIDTH + F3_HEIGHT/2)}" rpy="0 ${PI} 0" />
    </dynamixel_AX12_fixed>
    
    <bioloid_F2_revolute parent="left_arm_elbow_flex_servo" name="left_arm_elbow_flex" color="${color}" vlimit="3.14" llimit="-1.75" ulimit="1.75">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <axis xyz="0 1 0" />
    </bioloid_F2_revolute>
    
    <!-- left forearm flex -->
    <bioloid_F3_fixed parent="left_arm_elbow_flex" name="left_arm_forearm_F3_0" color="${color}">
      <origin xyz="0 0 ${AX12_HEIGHT/2 + F3_HEIGHT - 0.0015}" rpy="${PI} 0 ${PI/2}" />
    </bioloid_F3_fixed>
    
    <dynamixel_AX12_fixed parent="left_arm_forearm_F3_0" name="left_arm_forearm_flex_servo">
      <origin xyz="0 0 ${-(AX12_HEIGHT/2 + F2_DEPTH)}" rpy="${PI} 0 0" />
    </dynamixel_AX12_fixed>
    
    <bioloid_F2_revolute parent="left_arm_forearm_flex_servo" name="left_arm_forearm_flex" color="${color}" vlimit="3.14" llimit="-1.75" ulimit="1.75">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <axis xyz="0 1 0" />
    </bioloid_F2_revolute>
    
    <bioloid_F2_fixed parent="left_arm_forearm_flex" name="left_arm_forearm_F2_0" color="${color}">
      <origin xyz="0 0 ${AX12_HEIGHT/2 + F2_HEIGHT - 0.004}" rpy="0 ${PI} ${PI/2}" />
    </bioloid_F2_fixed>
    
    <!-- left wrist flex -->
    <dynamixel_AX12_revolute parent="left_arm_forearm_F2_0" name="left_arm_wrist_flex" vlimit="3.14" llimit="-1.75" ulimit="1.75">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <axis xyz="0 1 0" />
    </dynamixel_AX12_revolute>
    
    <bioloid_F3_fixed parent="left_arm_wrist_flex" name="left_arm_wrist_F3_0" color="${color}">
      <origin xyz="0 0 ${-AX12_HEIGHT - F3_HEIGHT/2}" rpy="${PI} 0 0" />
    </bioloid_F3_fixed>
    
    <!-- left gripper attach joint -->
    <bioloid_F3_fixed parent="left_arm_wrist_F3_0" name="left_arm_gripper_attach" color="${color}">
      <origin xyz="0 0 0.0005" rpy="${PI} 0 0" />
    </bioloid_F3_fixed>

   <!-- Attach the left gripper -->
   <gripper side="left" reflect="-1" parent="_arm_gripper_attach_link">
     <origin xyz="0 0 0" rpy="0 0 0" /> 
   </gripper>

  <joint name="kinect_joint" type="fixed">
    	<parent link="base_link" />
    	<child link="kinect_link" />
    	<origin xyz="0.04 0 0.15" rpy="0 0 0" />
	</joint>
<joint name="kinect_depth_joint" type="fixed">
         <origin xyz="0 0.0125 0.015" rpy="0 0 0" />
          <parent link="kinect_link" />
          <child link="kinect_depth_frame" />
      </joint>

      <link name="kinect_depth_frame">
      <inertial>
         <mass value="0.000001" />
         <origin xyz="0 0 0" />
         <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
            iyy="0.0001" iyz="0.0"
            izz="0.0001" />
         </inertial>
      </link>

      <joint name="kinect_depth_optical_joint" type="fixed">
         <origin xyz="0 0 0" rpy="${-PI/2} 0 ${-PI/2}" />
         <parent link="kinect_depth_frame" />
         <child link="kinect_depth_optical_frame" />
      </joint>

      <link name="kinect_depth_optical_frame">
         <inertial>
            <mass value="0.000001" />
            <origin xyz="0 0 0" />
            <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
               iyy="0.0001" iyz="0.0"
               izz="0.0001" />
         </inertial>
      </link>

      <joint name="kinect_rgb_joint" type="fixed">
         <origin xyz="0 -0.0125 0.01" rpy="0 0 0" />
         <parent link="kinect_link" />
         <child link="kinect_rgb_frame" />
      </joint>

      <link name="kinect_rgb_frame">
         <inertial>
         <mass value="0.000001" />
         <origin xyz="0 0 0" />
         <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
            iyy="0.0001" iyz="0.0"
            izz="0.0001" />
         </inertial>
      </link>

      <joint name="kinect_rgb_optical_joint" type="fixed">
         <origin xyz="0 0 0" rpy="${-PI/2} 0 ${-PI/2}" />
         <parent link="kinect_rgb_frame" />
         <child link="kinect_rgb_optical_frame" />
      </joint>

      <link name="kinect_rgb_optical_frame">
         <inertial>
            <mass value="0.000001" />
            <origin xyz="0 0 0" />
            <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
               iyy="0.0001" iyz="0.0"
               izz="0.0001" />
         </inertial>
      </link>



</robot>
