controller_list:
  - name: "right_arm_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - right_j1_joint
      - right_j2_joint
      - right_j3_joint
      - right_j4_joint
      - right_j5_joint
      - right_j6_joint
  - name: "left_arm_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints: 
      - left_j1_joint
      - left_j2_joint
      - left_j3_joint
      - left_j4_joint
      - left_j5_joint
      - left_j6_joint   
  - name: left_gripper_controller
    action_ns: gripper_action
    type: GripperCommand
    default: true
    joints:
      - left_gripper_finger_joint
  - name: right_gripper_controller
    action_ns: gripper_action
    type: GripperCommand
    default: true
    joints:
      - right_gripper_finger_joint
  - name: head_controller
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    joints:
      - head_tilt_joint
      - head_pan_joint
