controller_list:
  - name: fake_right_arm_controller
    joints:
      - right_j1_joint
      - right_j2_joint
      - right_j3_joint
      - right_j4_joint
      - right_j5_joint
      - right_j6_joint
  - name: fake_left_arm_controller
    joints:
      - left_j1_joint
      - left_j2_joint
      - left_j3_joint
      - left_j4_joint
      - left_j5_joint
      - left_j6_joint
  - name: fake_right_gripper_controller
    joints:
      - right_gripper_finger_joint
  - name: fake_left_gripper_controller
    joints:
      - left_gripper_finger_joint