gizmo:
# MoveIt-specific simulation settings
  moveit_sim_hw_interface:
    joint_model_group: controllers_initial_group_
    joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
  generic_hw_control_loop:
    loop_hz: 300
    cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
  hardware_interface:
    joints:
      - virtual_joint
      - left_j1_joint
      - left_j2_joint
      - left_j3_joint
      - left_j4_joint
      - left_j5_joint
      - left_j6_joint
      - left_gripper_finger_joint
      - head_pan_joint
      - head_tilt_joint
      - right_j1_joint
      - right_j2_joint
      - right_j3_joint
      - right_j4_joint
      - right_j5_joint
      - right_j6_joint
      - right_gripper_finger_joint
    sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  controller_list:
    - name: right_arm_controller
      action_ns: follow_joint_trajectory
      default: True
      type: FollowJointTrajectory
      joints:
        - right_j1_joint
        - right_j2_joint
        - right_j3_joint
        - right_j4_joint
        - right_j5_joint
        - right_j6_joint
    - name: left_arm_controller
      action_ns: follow_joint_trajectory
      default: True
      type: FollowJointTrajectory
      joints:
        - left_j1_joint
        - left_j2_joint
        - left_j3_joint
        - left_j4_joint
        - left_j5_joint
        - left_j6_joint
    - name: right_gripper_controller
      action_ns: follow_joint_trajectory
      default: True
      type: FollowJointTrajectory
      joints:
        right_gripper_finger_joint
    - name: left_gripper_controller
      action_ns: follow_joint_trajectory
      default: True
      type: FollowJointTrajectory
      joints:
        left_gripper_finger_joint